name: test

on:
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [16, 18, 20, latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - uses: actions/checkout@v4

      - run: |
          [[ "$(node main.mjs)" == "ok" ]] && echo ok

  deno:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [1.4, 1.37, v1.x]
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.version }}

      - uses: actions/checkout@v4

      - run: |
          [[ "$(deno run main.mjs)" == "ok" ]] && echo ok

  bun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [1.0.0, 1.0.6, latest]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.version }}

      - uses: actions/checkout@v4

      - run: |
          [[ "$(bun run main.mjs)" == "ok" ]] && echo ok
